enyo.depends(
  "sales_category.js",
  "cash_receipt.js",
  "list.js",
  "list_relations.js",
  "list_relations_box.js",
  "list_relations_editor_box.js",
  "receivable.js",
  "workspace.js"
);
enyo.depends(
  "comment_box.js",
  "list.js",
  "list_relations.js",
  "list_relations_editor_box.js",
  "grid_box.js",
  "workspace.js"
);
enyo.depends(
  "list.js",
  "list_relations.js",
  "list_relations_box.js",
  "dashboard.js",
  "workspace.js"
);
