(function () {
  "use strict";

  var lang = XT.stringsFor("en_US", {
    "_deceased": "Deceased",
    "_evictionInherited": "Eviction Inherited",
    "_evictionOrganic": "Eviction Organic",
    "_movedToOtherPangeaUnit": "Moved To Other Pangea Unit",
    "_neverMovedIn": "Never Moved In",
    "_noContactInfo": "No Contact Info",
    "_pangeaCCCCheck": "Pangea CCC Check",
    "_pangeaEVCCheck": "Pangea EVC Check",
    "_pangeaOther": "Pangea Other",
    "_pangeaSoldBldg": "Pangea Sold Bldg",
    "_pangeaTenantInViolation": "Pangea Tenant In Violation",
    "_pangeaUnstableBldgDeparture": "Pangea Unstable Bldg Departure",
    "_tenantMoveOutUnsatisfied": "Tenant Move Out/Unsatisfied",
    "_tenantChangeOfIncome": "Tenant Change Of Income",
    "_tenantFamilySituation": "Tenant Family Situation",
    "_tenantFoundAnotherApt": "Tenant Found Another Apt",
    "_tenantLostJob": "Tenant Lost Job",
    "_tenantMustMoveOutOfCity": "Tenant Must Move Out Of City",
    "_tenantPurchasedHome": "Tenant Purchased Home",
    "_tenantUnsatisfiedMaintenance": "Tenant Unsatisfied Maintenance",
    "_tenantUnsatisfiedNeighbors": "Tenant Unsatisfied Neighbors",
    "_tenantUnsatisfiedPM": "Tenant Unsatisfied PM",
    "_tenantUnsatisfiedRentIncrease": "Tenant Unsatisfied Rent Increase",
    "_tenantUnsatisfiedSafety": "Tenant Unsatisfied Saftey",
    "_unableToReachTenant": "Unable To Reach Tenant",
    "_eviction": "Eviction",
    "_terminated": "Terminated",
    "_other": "Other",
    "_oakParkRentalAssistance": "Oak Park Rental Assistance",
    "_HACC": "HACC",
    "_featherFist": "FeatherFist",
    "_chicagoDeptOfHumanSvcs": "Chicago Dept of Human Svcs",
    "_heartlandAlliance": "Heartland Alliance",
    "_catholicCharities": "Catholic Charities",
    "_innerVoice": "Inner Voice",
    "_CCHC": "CCHC",
    "_DFSS": "DFSS",
    "_HAP": "HAP",
    "_AFCHousing": "AFC Housing",
    "_pathways": "Pathways",
    "_thresholds": "Thresholds",
    "_parkForestHousing": "Park Forest Housing",
    "_maywoodHousingAuthority": "Maywood Housing Authority",
    "_section8IHA": "Section 8_IHA",
    "_section8HABC": "Section 8_HABC",
    "_unityParenting": "Unity Parenting",
    "_lowIncomeHousingTrustFund": "Low Income Housing Trust Fund",
    "_TIP": "TIP",
    "_DOWE": "DOWE",
    "_kaleidoscopeSubsidy": "Kaleidoscope Subsidy",
    "_casaCentral": "Casa Central",
    "_interFaith": "Inter Faith",
    "_HIPProgram": "HIP Program",
    "_chesapeakeConnection": "Chesapeake Connection",
    "_housingOpportunityForWomen": "Housing Opportunity For Women",
    "_beaconTherapeuticHomelessServices": "Beacon Therapeutic Homeless Services",
    "_youthOutreach": "Youth Outreach",
    "_williamDecree": "Williams Decree",
    "_lawrenceHallYouthServices": "Lawrence Hall Youth Services",
    "_childrenBureauInc": "Children Bureau Inc.",
    "_projectPlase": "Project Plase",
    "_metropolitanFamilyServices": "Metropolitan Family Services",
    "_section8": "Section 8",
    "_SCRIE": "SCRIE",
    "_TIC": "TIC",
    "_rentControl": "Rent Control",
    "_EDENIncShelterCarePlus": "EDEN INC. - Shelter Care Plus",
    "_CLC": "CLC",
    "_DHAP": "DHAP",
    "_FEMA": "FEMA",
    "_harrisCounty": "Harris County",
    "_realEstate": "Real Estate",
    "_realEstatePortfolios": "Portfolios",
    "_realEstateZones": "Zones",
    "_realEstateLeases": "Leases",
    "_residential": "Residential",
    "_commercial": "Commercial",
    "_zone": "Zone",
    "_scheduledMoveOutDate": "Scheduled Move Out Date",
    "_publicAssistanceProgram": "Public Assistance Program",
    "_reasonForLeaving": "Reason For Leaving",
    "_crmacctId": "CRM Account Id",
    "_moveInDate": "Move In Date",
    "_vacatedDate": "Vacated Date",
    "_movedWithin": "Moved Within",
    "_unitId": "Unit Id",
    "_accountId": "Account Id",
    "_accountingClosingDate": "Accounting Closing Date",
    "_portfolio": "Portfolio",
    "_realEstateUnits": "Units",
    "_realEstateBuildings": "Buildings",
    "_realEstateUnit": "Unit",
    "_realEstateBuilding": "Building",
    "_unitName": "Unit Name",
    "_id": "Id",
    "_buildingId": "Buildings Id",
    "_building": "Building",
    "_unitTypeId": "Unit Type Id",
    "_createdAt": "Created At",
    "_category": "Category",
    "_totalArea": "Total Area",
    "_floorNumber": "Floor Number",
    "_address": "Address",
    "_city": "City",
    "_state": "State",
    "_zipCode": "Zip Code",
    "_majorIntersection": "Major Intersection",
    "_bedrooms": "Bedrooms",
    "_bathrooms": "Bathrooms",
    "_targetRent": "Target Rent",
    "_targetDeposit": "Target Deposit",
    "_leaseID": "Lease Id",
    "_buildingName": "Building Name",
    "_portfolioId": "Portfolio Id",
    "_zoneId": "Zone Id",
    "_buildingTypeId": "Building Type Id",
    "_officeId": "Office Id",
    "_promoId": "Promo Id",
    "_parkingVendorId": "Parking Vendor Id",
    "_assetAcquisitionDate": "Asset Acquisition Date",
    "_assetSaleDate": "Asset Sale Date",
    "_floors": "Floors",
    "_neighborhood": "Neighborhood",
    "_communityName": "Community Name",
    "_leasingAgencyApproved": "Leasing Agency Approved",
    "_unitCount": "Unit Count"
  });

  if (typeof exports !== 'undefined') {
    exports.language = lang;
  }
}());
