(function() {
  "use strict";
  
  var lang = XT.stringsFor('en_US', {
    '_accounting' : 'Accounting',
    '_cashReceipts' : 'Cash Receipts',
    '_tenantLedgers' : 'Tenant Ledgers',
    '_invoices' : 'Invoices',
    '_salesOrders' : 'Sales Orders',

    //billing
    "_accountsReceivable": "Accounts Receivable",
    "_americanExpress": 'American Express',
    "_asOf": "As Of",
    "_application": "Application",
    "_applications": "Applications",
    "_applied": "Applied",
    "_appliedAmount": "Applied Amount",
    "_applyARMemos": "Apply Receivable Memos",
    "_applyBalanceAs": "Apply Balance As",
    "_applyBalanceToCreditMemo": "Credit Memo",
    "_applyBalanceToCustomerDeposit": "Customer Deposit",
    "_autoCloseARIncident": "Auto Close Incidents when Invoid Paid",
    "_autoCreditWarnLateCustomers": "Credit warn Customers when Late",
    "_billing": "Billing",
    "_billingDescription": "Corporate Relationship Management",
    "_cashReceipt": "Cash Receipt",
    "_cashReceiptApplications": "Cash Receipt Applications",
    "_cashReceipts": "Cash Receipts",
    "_cashReceiptCurrencyMismatchWarning": "Cash Receipt currency {cr_currency} does not match Bank Account Currency {ba_currency}",
    "_certifiedCheck": 'Certified Check',
    "_check": 'Check',
    "_configureAR": "Configure Billing",
    "_createNewCurrency": "Create New Currency",
    "_credits": "Credits",
    "_creditTaxDiscount": "Credit Taxes for Early Payment Discounts",
    "_customerDeposit": "Customer Deposit",
    "_debits": "Debits",
    "_defaultARIncidentStatus": "Default Incident Category",
    "_defaultAutoCreditWarnGraceDays": "Default Grace Period Days",
    "_discover": 'Discover',
    "_distributionDate": "Distribution Date",
    "_applicationDate": "Application Date",
    "_editAROpenItem": "Edit Receivables",
    "_enableCustomerDeposits": "Enable Customer Deposits",
    "_fundsType": "Type of Funds",
    "_hideApplyToBalance": "Hide 'Apply to Balance' Action",
    "_isPosted": "Posted",
    "_isNotPosted": "Unposted",
    "_maintainCashReceipts": "Maintain Cash Receipts",
    "_maintainCreditMemos": "Maintain Credit Memos",
    "_maintainCurrencies": "Maintain Currencies",
    "_maintainCustomerEmailProfiles": "Maintain Customer Email Profiles",
    "_maintainMiscInvoices": "Maintain Invoices",
    "_maintainSalesCategories": "Maintain Sales Categories",
    "_mastercard": 'Mastercard',
    "_nextARMemoNumber": "Next Receivables Memo",
    "_nextCashRcptNumber": "Next Cash Receipt",
    "_otherCreditCard": 'Other Credit Card',
    "_orderNumber": "Order #",
    "_other": 'Other',
    "_payment": 'Payment',
    "_postARDocuments": "Post Receivable Documents",
    "_postCashReceipts": "Post Cash Receipts",
    "_postCashPayment": "Post Cash Payment",
    "_postMiscInvoices": "Post Invoices",
    "_printInvoices": "Print Invoices",
    "_printOnPost": "Print on Post",
    "_receivable": "Receivable",
    "_receivables": "Receivables",
    "_recordReceiptAs": "Record Receipt As",
    "_recurringInvoiceBuffer": "Recurring Invoice Buffer Days",
    "_salesCategories": "Sales Categories",
    "_salesCategory": "Sales Category",
    "_salesOrderPaymentOverapplicationWarn": "The payment amount entered is larger than the Sales Order balance. Are you sure you would like to overpay this Sales Order?",
    "_salesOrderPaymentFailure": "We encountered a problem posting payment to this Sales Order",
    "_salesOrderPaymentSuccess": "Payment Successfully posted to Sales Order",
    "_taxes": "Taxes",
    "_taxTotal": "Tax Total",
    "_unposted": "Unposted",
    "_useCustomerDeposit": "Use Customer Deposit",
    "_viewAROpenItems": "View Receivables",
    "_viewCashReceipts": "View Cash Receipts",
    "_viewCreditMemos": "View Credit Memos",
    "_viewMiscInvoices": "View Invoices",
    "_visa": 'Visa',
    "_void": "Void",
    "_voidPostedARCreditMemos": "Void Posted Returns",
    "_voidPostedCashReceipts": "Void Posted Cash Receipts",
    "_voidPostedInvoices": "Void Posted Invoices",
    "_wireTransfer": 'Wire Transfer',

    // Application errors
    "_taxesMustNotBeGreater": "The Tax Total may not be greater than the Amount",

    //purchasing
    "_correctToEarliestDate?": "The due date does not fall within the lead time for this Item Source. Would you like it corrected?",
    "_correctToMinimumQuantity?": "The quantity is below the minimum order quantity for this Item Source. Would you like it corrected?",
    "_correctToMultipleQuantity?": "The quantity does not fall within the order multiple quantity for this Item Source. Would you like it corrected?",
    "_createSupplyForSalesOrders": "Auto Create for Sales Orders",
    "_CopyPRtoPOItem": "Copy to Order",
    "_DefaultPrintPOOnSave": "Print on Save",
    "_defaultShipVia": "Default Ship Via",
    "_earliestDate": "Earliest Date",
    "_errorStandardCostRequired": "The Item {number} can not be used because has no standard cost.",
    "_freightSubtotal": "Freight Subtotal",
    "_itemSource": "Item Source",
    "_itemSourceItemInactive": "Item Source can not be active when Item is inactive",
    "_itemSources": "Item Sources",
    "_isPurchased": "Purchased",
    "_isDropShip": "Drop Ship",
    "_isMisc": "Miscellaneous",
    "_maintainPurchaseOrders": "Maintain Purchase Orders",
    "_maintainPurchaseEmailProfiles": "Maintain Purchase Email Profiles",
    "_maintainPurchaseTypes": "Maintain Purchase Types",
    "_manufacturer": "Manufacturer",
    "_manufacturerItem": "Mfg. Item",
    "_maximumDesiredCost": "Maximum Cost",
    "_na": "N/A",
    "_noManufacturerNumber": "No Manufacturer Item",
    "_noVendorNumber": "No Vendor Item",
    "_priceType": "Price Type",
    "_purchase": "Purchase",
    "_purchasing": "Purchasing",
    "_purchaseEmailProfile": "Email Profile",
    "_purchaseEmailProfiles": "Purchase Email",
    "_purchaseOrder": "Purchase Order",
    "_purchaseOrderLine": "Purchase Order Line",
    "_purchaseOrderWorkflow": "Purchase Workflow",
    "_purchaseOrders": "Purchase Orders",
    "_purchaseRequest": "Purchase Request",
    "_purchaseRequests": "Purchase Requests",
    "_purchaseType": "Purchase Type",
    "_purchaseTypes": "Purchase Types",
    "_quantityBreak": "Quantity Break",
    "_releaseDate": "Release Date",
    "_ranking": "Ranking",
    "_RequirePOTax": "Require Tax",
    "_RequireStdCostForPOItem": "Require Standard Cost",
    "_transactedPoNotUnreleased": "This Purchase Order has transactions and can not be Unreleased.",
    "_supply": "Supply",
    "_unitRatio": "Unit Ratio",
    "_UseEarliestAvailDateOnPOItem": "Use Earliest Date",
    "_vendorItem": "Vendor Item",
    "_vendorItemNumber": "VendorItemNumber",
    "_viewPurchaseOrders": "View Purchase Orders",
    "_vouchered": "Vouchered",
    "_warnMaxCostExceeded": "The price is above the maximum desired cost of {maximumDesiredCost} for this Item."
  });

  if (typeof exports !== "undefined") {
    exports.language = lang;
  }
}());
/*jshint node:true, indent:2, curly:false, eqeqeq:true, immed:true,
latedef:true, newcap:true, noarg:true, regexp:true, undef:true,
strict:true, trailing:true, white:true */
/*global XT:true */

(function () {
  "use strict";

  var lang = XT.stringsFor("en_US", {
    "_acceptsBackOrders": "Accepts Back Orders",
    "_acceptsPartialShipments": "Accepts Partial Shipments",
    "_allowASAPShipSchedules": "Allow ASAP Schedule Dates",
    "_allowDiscounts": "Allow Price Discounts",
    "_allowFreeFormShiptos": "Allow Free Form Ship-Tos",
    "_authorizedCredit": "Authorized Credit",
    "_autoAllocateCreditMemos": "Allocate Credit Memos to New Sales Order on Save",
    "_autoSelectForBilling": "Check 'Select for Billing' option on Ship Order",
    "_bookings": "Bookings",
    "_convert": "Convert",
    "_creditControl": "Credit Control",
    "_creditMemo": "Credit Memo",
    "_current": "Current",
    "_currentDate": "Current Date",
    "_customerDefaults": "Customer Defaults",
    "_customerTypes": "Customer Types",
    "_cutOffDay": "Cutoff Day",
    "_dateControl": "Date Control",
    "_disableSalesOrderPriceOverride": "Disallow Override of Sale Price on Sales Order",
    "_doNotUpdate": "Do Not Update",
    "_enableSOShipping": "Enable Shipping Interface from Sales Order screen",
    "_firmSalesOrdersWhenAddedToPackingList": "Firm Sales Orders when added to Packing List Batch",
    "_fiveYears": "Five Years",
    "_freightPricing": "Freight Pricing",
    "_hideSOMiscCharge": "Hide Misc. Charge on Sales Order screen",
    "_ignoreIfDiscounted": "Ignore if Discounted",
    "_includePackageWeight": "Include Package Weight in Freight Calculation",
    "_invoice": "Invoice",
    "_invoiceDateSource": "Invoice Date Source",
    "_maintainCustomerEmailProfiles": "Maintain Customer Email Profiles",
    "_maintainSalesEmailProfiles": "Maintain Sales Email Profiles",
    "_postCustomerChanges": "Post Customer Changes",
    "_postSalesOrderChanges": "Post Sales Order Changes",
    "_priceControl": "Price Control",
    "_priceEffectiveDate": "Price Effective Date",
    "_pricing": "Pricing",
    "_pricingOnLineItemEdits": "Pricing on Line Item edits",
    "_printCreditMemos": "Print Credit Memos",
    "_printOnSave": "Print on Save",
    "_process": "Process",
    "_processCreditCards": "Process Credit Cards",
    "_prompt": "Prompt",
    "_restrictCreditMemos": "Restrict Credit Memos to Items on their Apply-to Document",
    "_sales": "Sales",
    "_salesDescription": "Customer and Sales Order Management",
    "_salesHistory": "Sales History",
    "_salesOrder": "Sales Order",
    "_scheduled": "Scheduled",
    "_scheduledDate": "Scheduled Date",
    "_shipControl": "Ship Control",
    "_shipDate": "Ship Date",
    "_showQuotesAfterConverted": "Show Quotes after Conversion to SO",
    "_showSaveAndAddbutton": "Show 'Save and Add to Packing List' Button on Sales Order",
    "_staleAnalysisWarning": "Free trial demo analysis data will not be updated from your live changes.",
    "_termsType": "Terms Type",
    "_thisWeek": "This Week",
    "_thisMonth": "This Month",
    "_thisYear": "This Year",
    "_timeFrame": "Time Frame",
    "_twoYears": "Two Years",
    "_today": "Today",
    "_update": "Update",
    "_useCalculatedFreightPricing": "Use calculated Freight values by default",
    "_usePromiseDates": "Enable Promise Dates",
    "_viewSalesHistory": "View Sales History"
  });

  if (typeof exports !== 'undefined') {
    exports.language = lang;
  }
}());
