enyo.depends(
  //sales
  "account.js",
  "configure.js",
  "contact.js",
  "incident.js",
  "item.js",
  "invoice.js",
  "opportunity.js",
  "to_do.js",
  "startup.js",
  "static.js"
);
enyo.depends(
  //billing
  "account.js",
  "configure.js",
  "sales_category.js",
  "sales_order.js",
  "receivable.js",
  "static.js",
  "cash_receipt.js",
  "startup.js"
);
enyo.depends(
  //purchasing
  "characteristic.js",
  "configure.js",
  "item_site.js",
  "item_source.js",
  "purchase_order.js",
  "vendor.js",
  "static.js",
  "startup.js"
);

